version: '3.8'
services:
  ray-head:
    image: rayproject/ray-ml:latest-cpu
    container_name: ray-head
    command: >
      tail -f /dev/null
    network_mode: host
  ray-worker:
    image: rayproject/ray-ml:latest-cpu
    container_name: ray-worker
    command: >
      tail -f /dev/null
    network_mode: host
    depends_on:
      - ray-head
